
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Trainee
 */
		

public class InsuranceMock extends javax.swing.JFrame {
    String strComprehensive = "No";
    char chrClass = 'A';
    int intAge;
    int intValuation;
    int intMileage;
    String strClaimInLastFiveYears = "No";
    /**
     * Creates new form InsuranceMock
     */
    public InsuranceMock() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtMileage = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtValuation = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMakeModel = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        txtRegistration = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtAnnual = new javax.swing.JTextField();
        cboComprehensive = new javax.swing.JComboBox<>();
        cboNoClaims = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txtMonthly = new javax.swing.JTextField();
        cboCC = new javax.swing.JComboBox<>();
        btnCalculate = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();

        jTextField2.setBackground(new java.awt.Color(36, 47, 65));
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Enter your full name");
        jTextField2.setBorder(null);
        jTextField2.setCaretColor(new java.awt.Color(204, 204, 204));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FULL NAME");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jTextField3.setBackground(new java.awt.Color(36, 47, 65));
        jTextField3.setForeground(new java.awt.Color(204, 204, 204));
        jTextField3.setText("Enter your full name");
        jTextField3.setBorder(null);
        jTextField3.setCaretColor(new java.awt.Color(204, 204, 204));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FULL NAME");

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jTextField4.setBackground(new java.awt.Color(36, 47, 65));
        jTextField4.setForeground(new java.awt.Color(204, 204, 204));
        jTextField4.setText("Enter your full name");
        jTextField4.setBorder(null);
        jTextField4.setCaretColor(new java.awt.Color(204, 204, 204));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FULL NAME");

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 102, 0));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("     I & The Basics Ltd");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carIns.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" CALCULATOR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 201, 274, 15));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ESTIMATED ANNUAL MILEAGE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 131, 257, 25));

        txtMileage.setBackground(new java.awt.Color(36, 47, 65));
        txtMileage.setForeground(new java.awt.Color(204, 204, 204));
        txtMileage.setBorder(null);
        txtMileage.setCaretColor(new java.awt.Color(204, 204, 204));
        txtMileage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMileageFocusLost(evt);
            }
        });
        txtMileage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMileageActionPerformed(evt);
            }
        });
        jPanel1.add(txtMileage, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 217, 27));

        jPanel3.setBackground(new java.awt.Color(204, 102, 0));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("  X");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("AGE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 222, 184, 25));

        txtAge.setBackground(new java.awt.Color(36, 47, 65));
        txtAge.setForeground(new java.awt.Color(204, 204, 204));
        txtAge.setBorder(null);
        txtAge.setCaretColor(new java.awt.Color(204, 204, 204));
        txtAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAgeFocusLost(evt);
            }
        });
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 217, 27));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 292, 274, 15));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("COMPREHENSIVE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 313, 184, 25));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 383, 274, 15));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("VALUATION");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 404, 184, 25));

        txtValuation.setBackground(new java.awt.Color(36, 47, 65));
        txtValuation.setForeground(new java.awt.Color(204, 204, 204));
        txtValuation.setBorder(null);
        txtValuation.setCaretColor(new java.awt.Color(204, 204, 204));
        txtValuation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValuationFocusLost(evt);
            }
        });
        txtValuation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValuationActionPerformed(evt);
            }
        });
        jPanel1.add(txtValuation, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 441, 217, 27));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 474, 274, 15));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 383, 274, 15));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 201, 274, 15));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CLAIM IN LAST 5 YEARS");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 404, 226, 25));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("MAKE, MODEL");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 131, 184, 25));

        txtMakeModel.setBackground(new java.awt.Color(36, 47, 65));
        txtMakeModel.setForeground(new java.awt.Color(204, 204, 204));
        txtMakeModel.setBorder(null);
        txtMakeModel.setCaretColor(new java.awt.Color(204, 204, 204));
        txtMakeModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMakeModelActionPerformed(evt);
            }
        });
        jPanel1.add(txtMakeModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 168, 217, 27));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 610, 220, 15));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("VEHICLE CC");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 222, 184, 25));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 292, 274, 15));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("REGISTRATION");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 313, 184, 25));

        txtRegistration.setBackground(new java.awt.Color(36, 47, 65));
        txtRegistration.setForeground(new java.awt.Color(204, 204, 204));
        txtRegistration.setBorder(null);
        txtRegistration.setCaretColor(new java.awt.Color(204, 204, 204));
        txtRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistrationActionPerformed(evt);
            }
        });
        jPanel1.add(txtRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 350, 217, 27));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Annual Total: ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 580, -1, 41));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Please Enter your details to get a quote");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 56, 512, 41));

        txtAnnual.setEditable(false);
        txtAnnual.setBackground(new java.awt.Color(36, 47, 65));
        txtAnnual.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtAnnual.setForeground(new java.awt.Color(255, 255, 255));
        txtAnnual.setBorder(null);
        txtAnnual.setCaretColor(new java.awt.Color(204, 204, 204));
        txtAnnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnnualActionPerformed(evt);
            }
        });
        jPanel1.add(txtAnnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, 217, -1));

        cboComprehensive.setBackground(new java.awt.Color(36, 47, 65));
        cboComprehensive.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "No", "Yes" }));
        cboComprehensive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboComprehensiveActionPerformed(evt);
            }
        });
        jPanel1.add(cboComprehensive, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 120, -1));

        cboNoClaims.setBackground(new java.awt.Color(36, 47, 65));
        cboNoClaims.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "No", "yes" }));
        cboNoClaims.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNoClaimsActionPerformed(evt);
            }
        });
        jPanel1.add(cboNoClaims, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 436, 90, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Monthly Total: ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 533, -1, 41));

        txtMonthly.setEditable(false);
        txtMonthly.setBackground(new java.awt.Color(36, 47, 65));
        txtMonthly.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtMonthly.setForeground(new java.awt.Color(255, 255, 255));
        txtMonthly.setBorder(null);
        txtMonthly.setCaretColor(new java.awt.Color(204, 204, 204));
        txtMonthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonthlyActionPerformed(evt);
            }
        });
        jPanel1.add(txtMonthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, 217, -1));

        cboCC.setBackground(new java.awt.Color(36, 47, 65));
        cboCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "2000CC or more", "1500cc - 1999cc", "1000cc - 1499cc", "800cc - 999cc", "799cc or less" }));
        cboCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCCActionPerformed(evt);
            }
        });
        jPanel1.add(cboCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 253, 130, -1));

        btnCalculate.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        btnCalculate.setText("CALCULATE");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 540, 300, 80));

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 474, 274, 15));

        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, 220, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMileageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMileageActionPerformed
        intMileage = Integer.parseInt(txtMileage.getText());
    }//GEN-LAST:event_txtMileageActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        intAge = Integer.parseInt(txtAge.getText());
    }//GEN-LAST:event_txtAgeActionPerformed
    
    private void txtValuationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValuationActionPerformed
        try {
                intValuation = Integer.parseInt(txtAge.getText());
                }
                catch(Exception e) {
                    JOptionPane.showMessageDialog(null, "Valuation must be numeric");
                    txtValuation.setText("");
                }
    }//GEN-LAST:event_txtValuationActionPerformed
    private void txtMakeModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMakeModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMakeModelActionPerformed

    private void txtRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistrationActionPerformed

    private void txtAnnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnnualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnnualActionPerformed

    private void txtMonthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonthlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonthlyActionPerformed

    private void cboComprehensiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboComprehensiveActionPerformed
        // TODO add your handling code here:
        strComprehensive = cboComprehensive.getSelectedItem().toString();
        System.out.println(strComprehensive);
    }//GEN-LAST:event_cboComprehensiveActionPerformed

    private void cboCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCCActionPerformed
        // TODO add your handling code here:
        String CC = cboCC.getSelectedItem().toString(); // Grabs selected item and converts it to a string
        switch (CC) {
            case ("2000CC or more"): chrClass = 'A'; break;
            case ("1500cc - 1999cc"): chrClass = 'B'; break;
            case ("1000cc - 1499cc"): chrClass = 'C'; break;
            case ("800cc - 999cc"): chrClass = 'D'; break;
            case ("799cc or less"): chrClass = 'E'; break;
        }
        System.out.println(chrClass);
    }//GEN-LAST:event_cboCCActionPerformed

    private void txtAgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAgeFocusLost
        try {
        intAge = Integer.parseInt(txtAge.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Age must be numeric");
            txtAge.setText("");
        }
    }//GEN-LAST:event_txtAgeFocusLost

    private void txtValuationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValuationFocusLost
        try {
        intValuation = Integer.parseInt(txtAge.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter a valuation");
            txtValuation.setText("");
        }
    }//GEN-LAST:event_txtValuationFocusLost

    private void txtMileageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMileageFocusLost
        try {
        intMileage = Integer.parseInt(txtMileage.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter a mileage");
            txtMileage.setText("");
        }
    }//GEN-LAST:event_txtMileageFocusLost

    private void cboNoClaimsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNoClaimsActionPerformed
        strClaimInLastFiveYears = cboNoClaims.getSelectedItem().toString();
    }//GEN-LAST:event_cboNoClaimsActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        final double FULLRATE = 2000;
        double dblPremium = FULLRATE;
        
        if (txtAge.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Age not filled in");
            txtAge.requestFocus();
        }
        else if (txtMileage.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter mileage");
            txtMileage.requestFocus();
            
        }
        else {
        if (intAge < 25) {
            if (strClaimInLastFiveYears.equals("No") && chrClass == 'D' || chrClass == 'E')
                dblPremium = FULLRATE * 0.8;
        }
        else {
            if (strClaimInLastFiveYears.equals("No")) {
                switch (chrClass) {
                    case 'A': dblPremium = FULLRATE * 0.8; break;
                    case 'B': dblPremium = FULLRATE * 0.7; break;
                    case 'C': dblPremium = FULLRATE * 0.6; break;
                    case 'D': dblPremium = FULLRATE * 0.5; break;
                    case 'E': dblPremium = FULLRATE * 0.4; break;
                }
            }
        }
        
        if (intMileage <= 6000)
            dblPremium = dblPremium * 0.95; 
            
        if (strComprehensive.equals("No"))
            dblPremium = dblPremium * 0.5;
        
        DecimalFormat twoDForm = new DecimalFormat("#.##"); // Formats to 2 decimal points
        
        txtAnnual.setText("€" + String.valueOf(twoDForm.format(dblPremium)));
        double monthly = (dblPremium / 12) + 5;
        txtMonthly.setText("€" + String.valueOf(twoDForm.format(monthly)));
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsuranceMock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsuranceMock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsuranceMock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsuranceMock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsuranceMock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JComboBox<String> cboCC;
    private javax.swing.JComboBox<String> cboComprehensive;
    private javax.swing.JComboBox<String> cboNoClaims;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAnnual;
    private javax.swing.JTextField txtMakeModel;
    private javax.swing.JTextField txtMileage;
    private javax.swing.JTextField txtMonthly;
    private javax.swing.JTextField txtRegistration;
    private javax.swing.JTextField txtValuation;
    // End of variables declaration//GEN-END:variables
}
